// Luast v1.x deobfuscator — static/source-only profile.
//
// Target shape observed in samples generated by luast.clv.cloud:
//   local T = {}
//   T[128] = { scalar constants, helper functions, ... }
//   ... T[128][1234] ...
// plus flattened numeric state machines around those accessors.
//
// This engine deliberately never executes Lua/Luau or Roblox APIs. It first
// resolves immutable scalar object-table slots, then applies the repository's
// existing conservative constant/dispatcher passes.

import { Deobfuscator, DeobfuscateContext, DeobfuscateResult } from "../types";
import { renameObfuscatedIdentifiers } from "../utils/lua-utils";
import { inlineIndexedObjectTableLookups } from "../passes/static-resolve";
import { foldConstants } from "../passes/constant-fold";
import { flattenStateDispatchers } from "../passes/state-dispatch-flattener";
import { recoverFunctionLevelVm } from "../passes/function-level-vm";
import { recoverBinaryTreeDispatch } from "../passes/binary-tree-dispatch";
import { validateLuaSource } from "../utils/validate";
import { analyzeLuastSource, rejectLuastBadRewrites } from "../passes/luast-analysis";

function applyPass(
  current: string,
  name: string,
  fn: () => { result: string; changed?: number; folded?: number; notes?: string[] },
  notes: string[],
  log: (msg: string) => void,
): string {
  try {
    const r = fn();
    const changed = r.changed ?? r.folded ?? 0;
    if (changed > 0 && r.result !== current) {
      notes.push(...(r.notes ?? []).slice(0, 8));
      log(`luast: ${name} changed ${changed}`);
      return r.result;
    }
  } catch (e: unknown) {
    log(`luast: ${name} skipped (${e instanceof Error ? e.message : String(e)})`);
  }
  return current;
}

export class LuastDeobfuscator implements Deobfuscator {
  id = "luast" as const;
  name = "Luast v1.x Deobfuscator";
  description =
    "Static Luast v1.x object-table recovery plus conservative constant and flattened-dispatch reconstruction.";

  detect(input: string) {
    let score = 0;
    const evidence: string[] = [];
    if (/generated\s+by\s+luast\s+v\d+(?:\.\d+){0,2}/i.test(input)) {
      score += 0.62;
      evidence.push("Luast generator banner");
    }
    if (/local\s+[A-Za-z_]\w*\s*=\s*\{\s*\}\s*;\s*[A-Za-z_]\w*\s*\[\s*\d+\.?\s*\]\s*=\s*\{/i.test(input)) {
      score += 0.18;
      evidence.push("indexed object-table assignment");
    }
    if (/(?:while\s+true\s+do|if\s+[A-Za-z_]\w*\s*<\s*\d+\.?\s*then)[\s\S]{0,5000}\bcontinue\b/i.test(input)) {
      score += 0.10;
      evidence.push("flattened numeric dispatcher shape");
    }
    if (/\b(?:local\s+akR|local\s+[A-Za-z_]\w*)\b[\s\S]{0,3000}\[[0-9]+\.?\]\[[0-9]+\.?\]/i.test(input)) {
      score += 0.06;
      evidence.push("nested numeric table lookups");
    }
    if (score < 0.65) return null;
    return {
      obfuscator: "luast" as const,
      confidence: Math.min(0.99, score),
      evidence: evidence.join("; "),
    };
  }

  async deobfuscate(ctx: DeobfuscateContext): Promise<DeobfuscateResult> {
    const { input, log } = ctx;
    const notes: string[] = [];
    let work = input;
    let totalChanged = 0;

    if (!this.detect(input)) {
      return {
        success: false,
        deobfuscator: this.name,
        output: input,
        notes: ["Luast fingerprint did not match."],
        confidence: 0,
        obfuscator: "luast",
      };
    }

    // The Luast object-table pass is syntax-preserving and is the key
    // recovery step for this format. Re-run it around structural rewrites.
    work = applyPass(work, "Luast pool/type analysis", () => analyzeLuastSource(work), notes, log);
    const beforeIndexed = work.length;
    work = applyPass(work, "object-table recovery", () => inlineIndexedObjectTableLookups(work), notes, log);
    work = applyPass(work, "object-table recovery (2nd pass)", () => inlineIndexedObjectTableLookups(work), notes, log);
    totalChanged += Math.max(0, beforeIndexed - work.length);

    // Luast emits a numeric dispatcher around nearly every recovered helper.
    // Recover those branches before arithmetic folding; otherwise the state
    // variable and its branch-local values are easily mistaken for constants.
    try {
      const flattened = flattenStateDispatchers(work, {
        maxLoops: 96,
        maxStates: 512,
        maxOutput: Math.max(900_000, work.length * 3),
      });
      if (flattened.changed > 0 && flattened.result !== work && validateLuaSource(flattened.result).ok) {
        work = flattened.result;
        totalChanged += flattened.changed;
        notes.push(...flattened.notes.slice(0, 8));
        log(`luast: state dispatcher recovery changed ${flattened.changed} (${flattened.loops} loop(s), ${flattened.states} state(s))`);
      } else if (flattened.changed > 0) {
        log("luast: state dispatcher candidate rejected by syntax validation");
      }
    } catch (e: unknown) {
      log(`luast: state dispatcher recovery skipped (${e instanceof Error ? e.message : String(e)})`);
    }

    // Several generic arithmetic/VM passes are intentionally conservative,
    // but Luast's huge one-line dispatcher is sensitive to source-shape
    // rewrites. Only accept a dispatcher rewrite when the repository's static
    // validator confirms the whole output still parses.
    for (let round = 1; round <= 4; round++) {
      let changedThisRound = false;
      try {
        const candidate = recoverBinaryTreeDispatch(work, {
          maxLeaves: 1024,
          maxRewrites: 16,
        });
        if (candidate.changed > 0) {
          const v = validateLuaSource(candidate.result);
          if (v.ok && candidate.result !== work) {
            work = candidate.result;
            notes.push(...candidate.notes.slice(0, 8));
            log(`luast: binary-tree dispatcher recovery round ${round} changed ${candidate.changed}`);
            totalChanged += candidate.changed;
            changedThisRound = true;
          } else {
            log(`luast: binary-tree round ${round} rejected by syntax validation`);
          }
        }
      } catch (e: unknown) {
        log(`luast: binary-tree round ${round} skipped (${e instanceof Error ? e.message : String(e)})`);
      }

      if (!changedThisRound) break;
      try {
        const indexed = inlineIndexedObjectTableLookups(work);
        if (indexed.changed > 0 && validateLuaSource(indexed.result).ok) {
          work = indexed.result;
          notes.push(...indexed.notes);
          totalChanged += indexed.changed;
        }
      } catch {
        // best effort
      }
    }

    // A final constant-fold attempt is accepted only when syntax remains
    // valid. The stock folder can be too aggressive on Luau `if ... then` and
    // large flattened trees, so invalid candidates are discarded.
    try {
      const candidate = foldConstants(work, 2);
      if (candidate.folded > 0 && validateLuaSource(candidate.result).ok) {
        work = candidate.result;
        notes.push(...candidate.notes.slice(0, 8));
        totalChanged += candidate.folded;
        log(`luast: safe constant folding changed ${candidate.folded}`);
      }
    } catch {
      // best effort
    }

    work = applyPass(work, "Luast bad-rewrite quarantine", () => rejectLuastBadRewrites(work), notes, log);

    try {
      const renamed = renameObfuscatedIdentifiers(work);
      if (renamed.renamed > 0) {
        work = renamed.result;
        totalChanged += renamed.renamed;
        notes.push(`Renamed ${renamed.renamed} cryptic identifiers.`);
      }
    } catch {
      // Keep recovered source when rename heuristics cannot process a sample.
    }

    try {
      const v = validateLuaSource(work);
      notes.push(`Static validation: ${v.ok ? "valid" : `${v.issues.length} issue(s)`}.`);
    } catch {
      // Validation is reporting-only.
    }

    for (const n of notes) {
      if (/changed \d+/.test(n)) {
        const m = /changed (\d+)/.exec(n);
        if (m) totalChanged += Number(m[1]);
      }
    }

    const residual = /\bwhile\s+true\s+do\b|\[[0-9]{2,}\.?\]\[[0-9]{2,}\.?\]/.test(work);
    const confidence = Math.min(
      0.98,
      0.72 + Math.min(0.15, totalChanged / 20_000) + (residual ? 0.02 : 0.08),
    );

    return {
      success: work !== input,
      deobfuscator: this.name,
      output: work,
      notes: [
        `Luast static pipeline changed approximately ${totalChanged} source items.`,
        ...notes,
      ],
      confidence: work !== input ? confidence : 0,
      obfuscator: "luast",
    };
  }
}
